version: 2
updates:
  # Pip dependencies (via pyproject.toml)
  - package-ecosystem: "pip"
    directory: "/" # Root directory where your pyproject.toml is located
    schedule:
      interval: "weekly" # Check for updates weekly
    open-pull-requests-limit: 5

  # Conda dependencies
  - package-ecosystem: "conda"
    directory: "/" # If your conda environment.yml is in the root directory
    schedule:
      interval: "weekly" # Check for updates weekly
    open-pull-requests-limit: 5

  # GitHub Actions (for any workflows using specific actions or dependencies)
  - package-ecosystem: "github-actions"
    directory: "/" # Root directory of the repository
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
