version: 2
updates:
  # Pip dependencies (via pyproject.toml)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions (for any workflows using specific actions or dependencies)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
