name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
    unit-tests:
        name: Unit / ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os:
              - ubuntu-latest
              - windows-latest
              - macos-12
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-python@v5
            with:
              python-version: "${{ env.PYTHON_VERSION }}"

          - name: Install Hatch
            id: hatch
            shell: bash
            run: |
              pip install hatch

          - name: Run
            run: hatch run test:unit
