site_name: TemporalScope
nav:
  - Home: index.md
  - Methods:
      - Mean Absolute SHAP: methods/mean_absolute_shap.md
  - Usage: usage.md
  - Development Roadmap: roadmap.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python

theme:
  name: material
