[tool.poetry]
name = "temporalscope"
version = "0.1.0"
description = "TemporalScope: Model-Agnostic Temporal Feature Importance Analysis."
authors = ["Philip Ndikum <philip-ndikum@users.noreply.github.com>"]
license = "Apache License 2.0"
readme = "README.md"
packages = [{include = "temporalscope"}]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
shap = "^0.46.0"
borutashap = "^1.0.17"
pytest = "^8.3.2"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.2.4"
notebook = "^7.2.1"
ipykernel = "^6.29.5"
nbformat = "^5.10.4"
nbconvert = "^7.16.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
